### ISSUE TITLE
The Question about the HausdorffLoss

### ISSUE THREAD

**Issue by abcxubu** [SilmarilBearer/HausdorffLoss#3]
Thanks so much for this wonderful work. I learned a lot from this work. But I have a question about it, i.e. in hausdorff_loss.py, there have:
    def distance_field(self, img: np.ndarray) -> np.ndarray:
        field = np.zeros_like(img)

        for batch in range(len(img)): 
            fg_mask = img[batch] > 0.5  

            if fg_mask.any():  
                bg_mask = ~fg_mask  

                fg_dist = edt(fg_mask)  
                bg_dist = edt(bg_mask)

                field[batch] = fg_dist + bg_dist

        return field
My question is why field[batch] is the sum of fg_dist, bg_dist? The only fg_dist is not enough? Thank you in advance. Hope to hear from you as soon as possible.

**Comment by PatRyg99** [comment]
For a binary mask EDT computes only distance for true pixels (with value of 1). Thus when calculating EDT only one time you get distance transform only for foreground mask (pixels with value of 0 stay as 0s). To calculate it for all pixels you need to invert the mask and run through EDT once more to obtain distance transform for background mask. 

When you sum those two masks you create unsigned distance field and when subtract either one from the other you create signed distance field (one with negative and positive values). In paper authors describe that they used unsigned fields but I've run a couple tests and both unsigned and signed fields as well as one way transforms e.g. foreground and background, seem viable. This may depend on imbalance between the segmentation classes and segmentation shapes in particular problem.

**Comment by abcxubu** [comment]
I see. Thanks again for your reply.
