### ISSUE TITLE
3D Kernel Shape

### ISSUE THREAD

**Issue by Chris-N-K** [SilmarilBearer/HausdorffLoss#6]
I have a question regarding your 3D kernel shape.
The shape of your 3D kernel is `3, 1, 3, 3` I'm not sure but shouldn't the shape be `1, 3, 3, 3`? The first dimension should be the channel, followed by D x H x W or not? At the Moment your kernel is D x C x H x W if I'm not completely mistaken. The reason is:

```Python
self.kernel3D = np.array([bound, cross, bound]) * (1 / 7)
# should be
self.kernel3D = np.stack([bound, cross, bound], 1) * (1 / 7)
```

If the shape of the kernel is on purpose I would like to understand the idea behind it :)
Thanks a lot for your work.

Best regards,
Chris

**Comment by PatRyg99** [comment]
Hi, sorry for the long wait. You're right, the shapes for 3D are mismatched. To be honest the erosion version is not really something that works - I've only fiddled with it for a while and haven't really used it or tested it.

**Comment by Chris-N-K** [comment]
Why do you think it does not work? I had the impression it did work fine.
I rewrote it in plain pytorch.

**Comment by PatRyg99** [comment]
I mean, I was under the impression that my implementation is not something that works correctly. As I remember correctly, the gradient propagation was not quite working.

I'm curious, you rewrote this erosion part to be in PyTorch and it seems to work? Did you manage to learn some models on it?

**Comment by Chris-N-K** [comment]
Yes I did but not as a sole loss, I combined it with a Dice. I got some improvements in the predictions and it did not impaired training performance much after the rewrite. I used it more as an penalty term to modify the Dice score.
